import { db } from '@/lib/db/client';
import { tasks, repositories, pullRequests, stages, projectRepos, activities } from '@/lib/db/schema';
import { eq, and } from 'drizzle-orm';
import { simpleGit } from 'simple-git';
import { getRepoWorkdir, ensureWorktree } from './worktree';
import { createOctokit } from '@/lib/github';
import { createId } from '@paralleldrive/cuid2';

export interface AutoPROptions {
  projectId: string;
  taskId: string;
  agentName?: string;
  agentEmail?: string;
}

export interface AutoPRResult {
  branch: string;
  commitSha: string | null;
  prNumber: number | null;
  prUrl: string | null;
  error?: string;
}

export async function commitAndPush(
  opts: AutoPROptions
): Promise<{ branch: string; commitSha: string | null; error?: string }> {
  const { projectId, taskId, agentName, agentEmail } = opts;

  // Find repo for this project
  const projRepo = await db.query.projectRepos.findFirst({
    where: eq(projectRepos.projectId, projectId),
    with: { repository: true },
  });

  if (!projRepo?.repository) {
    return { branch: '', commitSha: null, error: 'No repository linked to project' };
  }

  const repo = projRepo.repository;

  // Ensure repo is cloned
  try {
    const { workdir } = await ensureWorktree(projectId, repo.id);
  } catch (err) {
    return { branch: '', commitSha: null, error: `Failed to clone repository: ${(err as Error).message}` };
  }

  const workdir = getRepoWorkdir(projectId);

  const task = await db.query.tasks.findFirst({
    where: eq(tasks.id, taskId),
  });

  if (!task) {
    return { branch: '', commitSha: null, error: 'Task not found' };
  }

  const git = simpleGit(workdir);

  // Check if there are changes
  const status = await git.status();
  if (status.files.length === 0) {
    return { branch: '', commitSha: null, error: 'No changes to commit' };
  }

  const branch = `devrelay/${taskId.slice(0, 8)}`;

  try {
    // Create and switch to branch
    await git.checkoutLocalBranch(branch);

    // Stage all changes
    await git.add('.');

    // Commit with agent identity
    const commitName = agentName || 'DevRelay Agent';
    const commitEmail = agentEmail || 'agent@devrelay.local';
    const commitMsg = `[DevRelay] ${task.title}\n\nTask: ${taskId}\nProject: ${projectId}`;

    const commitResult = await git.commit(commitMsg, undefined, {
      '--author': `${commitName} <${commitEmail}>`,
    });

    if (!repo.accessToken) {
      return { branch, commitSha: commitResult.commit || null, error: 'No access token for push' };
    }

    const pushUrl = repo.remoteUrl.replace(
      'https://',
      `https://x-access-token:${repo.accessToken}@`
    );

    await git.push(pushUrl, branch, ['--set-upstream']);

    // Update task with branch and commit info
    await db
      .update(tasks)
      .set({
        gitBranch: branch,
        gitCommitSha: commitResult.commit || null,
        updatedAt: new Date().toISOString(),
      })
      .where(eq(tasks.id, taskId));

    return { branch, commitSha: commitResult.commit || null };
  } catch (err) {
    return { branch, commitSha: null, error: `Git error: ${(err as Error).message}` };
  }
}

export async function createPRForTask(
  opts: AutoPROptions
): Promise<{ prNumber: number | null; prUrl: string | null; error?: string }> {
  const { projectId, taskId } = opts;

  const task = await db.query.tasks.findFirst({
    where: eq(tasks.id, taskId),
  });

  if (!task?.gitBranch) {
    return { prNumber: null, prUrl: null, error: 'Task has no branch' };
  }

  const projRepo = await db.query.projectRepos.findFirst({
    where: eq(projectRepos.projectId, projectId),
    with: { repository: true },
  });

  if (!projRepo?.repository?.accessToken) {
    return { prNumber: null, prUrl: null, error: 'No access token' };
  }

  const repo = projRepo.repository;
  const repoToken = repo.accessToken!;
  const [owner, repoName] = repo.name.split('/');

  if (!owner || !repoName) {
    return { prNumber: null, prUrl: null, error: 'Invalid repo name format' };
  }

  try {
    const octokit = createOctokit(repoToken);
    const { data: pr } = await octokit.rest.pulls.create({
      owner,
      repo: repoName,
      title: `[DevRelay] ${task.title}`,
      head: task.gitBranch,
      base: repo.defaultBranch || 'main',
      body: `Auto-generated by DevRelay\n\nTask: ${task.title}\nTask ID: ${taskId}`,
    });

    const now = new Date().toISOString();

    // Find the appropriate stage (development = step 7, or the current in-progress stage)
    const inProgressStage = await db.query.stages.findFirst({
      where: and(
        eq(stages.projectId, projectId),
        eq(stages.status, 'in_progress'),
      ),
    });

    const prId = createId();
    await db.insert(pullRequests).values({
      id: prId,
      repositoryId: repo.id,
      prNumber: pr.number,
      title: pr.title,
      body: pr.body || null,
      state: 'open',
      sourceBranch: pr.head.ref,
      targetBranch: pr.base.ref,
      commitSha: task.gitCommitSha || pr.head.sha,
      devrelayStageId: inProgressStage?.id || null,
      devrelayTaskId: taskId,
      createdAt: pr.created_at,
      updatedAt: pr.updated_at,
    });

    // Update task with PR info
    await db
      .update(tasks)
      .set({
        status: 'in_review',
        updatedAt: now,
      })
      .where(eq(tasks.id, taskId));

    // If code review stage (step 8) is pending, start it
    const reviewStage = await db.query.stages.findFirst({
      where: and(eq(stages.projectId, projectId), eq(stages.step, 8)),
    });
    if (reviewStage && reviewStage.status === 'pending') {
      await db
        .update(stages)
        .set({ status: 'in_progress', startedAt: now })
        .where(eq(stages.id, reviewStage.id));
    }

    // Log activity
    await db.insert(activities).values({
      id: createId(),
      projectId,
      actorId: task.agentId || 'system',
      actorName: opts.agentName || 'DevRelay Agent',
      action: 'pr_created',
      target: taskId,
      metadata: JSON.stringify({ prNumber: pr.number, prUrl: pr.html_url, branch: task.gitBranch }),
      createdAt: now,
    });

    return { prNumber: pr.number, prUrl: pr.html_url };
  } catch (err) {
    return { prNumber: null, prUrl: null, error: `PR creation failed: ${(err as Error).message}` };
  }
}

export async function runAutoPR(opts: AutoPROptions): Promise<AutoPRResult> {
  // Step 1: Commit and push
  const commitResult = await commitAndPush(opts);
  if (commitResult.error) {
    return { branch: commitResult.branch, commitSha: commitResult.commitSha, prNumber: null, prUrl: null, error: commitResult.error };
  }

  // Step 2: Create PR
  const prResult = await createPRForTask(opts);
  return { branch: commitResult.branch, commitSha: commitResult.commitSha, prNumber: prResult.prNumber, prUrl: prResult.prUrl, error: prResult.error };
}
